---
title: "Comparison of IRE ORA from Human, Mouse, and Zebrafish"
output: html_notebook
---

```{r}
library(UpSetR)
library(metap)
```


## Import Results

```{r import-results}
zebrafishRes <- readRDS(here("R/GSEA/data/ora/zebrafish_gs.rds"))
mouseRes <- readRDS(here("R/GSEA/data/ora/mouse_gs.rds"))
humanRes <- readRDS(here::here("R/GSEA/data/ora/human_gs.rds"))

combinedRes <- data.frame(
  geneset = zebrafishRes$geneset,
  source = zebrafishRes$source,
  zeb_p = zebrafishRes$fisher_p,
  zeb_p3 = zebrafishRes$fisher_p_3,
  zeb_p5 = zebrafishRes$fisher_p_5
) %>%
  inner_join(mouseRes[c("geneset", "fisher_p", "fisher_p_3", "fisher_p_5")] %>%
              dplyr::rename(mouse_p = fisher_p, mouse_p3 = fisher_p_3, mouse_p5 = fisher_p_5),
            by="geneset") %>%
  inner_join(humanRes[c("geneset", "fisher_p", "fisher_p_3", "fisher_p_5")] %>%
              dplyr::rename(human_p = fisher_p, human_p3 = fisher_p_3, human_p5 = fisher_p_5),
            by="geneset") %>%
  rowwise() %>% 
  mutate(
    wilk_p = wilkinsonp(c(zeb_p, mouse_p, human_p), r=2)$p,
    wilk_p3 = wilkinsonp(c(zeb_p3, mouse_p3, human_p3), r=2)$p,
    wilk_p5 = wilkinsonp(c(zeb_p5, mouse_p5, human_p5), r=2)$p
  ) %>%
  ungroup() %>%
  mutate(
    wilk_adj = p.adjust(wilk_p, "bonferroni"),
    wilk_adj3 = p.adjust(wilk_p3, "bonferroni"),
    wilk_adj5 = p.adjust(wilk_p5, "bonferroni")
  )
dim(combinedRes)

sigRes <- combinedRes %>% 
  dplyr::filter(wilk_adj < 0.05 | wilk_adj3 < 0.05 | wilk_adj5 < 0.05)
dim(sigRes)  # 1,148 of 10,427 gene sets have significant over-representation of IRE genes

sigRes %>% View

# saveRDS(combinedRes, here("R/GSEA/data/combinedRes.rds"))
# saveRDS(sigRes, here("R/GSEA/data/sigRes.rds"))

combinedRes <- readRDS(here::here("R/GSEA/data/combinedRes.rds"))
sigRes <- readRDS(here::here("R/GSEA/data/sigRes.rds"))

sigRes %>% colnames

sigRes %>% write.csv(here::here("Manuscript/Supp_Tables/S1_OverRepresentation.csv"))
```

```{r}
sigRes %>% View
```









```{r}
wilkinsonp(zebrafishRes)
```








```{r}
zebrafishRes_top <- zebrafishRes %>% rowwise() %>% dplyr::arrange(fdr) %>% dplyr::slice(1:1000)
```

```{r}
mouseRes_top <- mouseRes %>%  dplyr::arrange(fdr) %>% dplyr::slice(1:1000)
```

```{r}
humanRes_top <- humanRes %>% arrange(fdr) %>% dplyr::slice(1:1000)
```

```{r}
all_top <- list(zebrafish = zebrafishRes_top$geneset,
                mouse = mouseRes_top$geneset,
                human = humanRes_top$geneset)

all_top %<>% fromList()
```

```{r}
upset_top <- upset(all_top,
                   nintersects = NA,
                   empty.intersections = TRUE)
upset_top

upset_top %>% export::graph2ppt(here::here("R/GSEA/fig/ora_comparison"))
```


```{r}
inner_join(zebrafishRes_top[, c("geneset")], mouseRes_top[, c("geneset")]) %>%
  inner_join(humanRes_top[, c("geneset")]) %>% View
```

```{r}
inner_join(zebrafishRes_top[, c("geneset")], mouseRes_top[, c("geneset")]) %>% dim
```

```{r}
inner_join(humanRes_top[, c("geneset")], mouseRes_top[, c("geneset")]) %>% dim
```

```{r}
inner_join(zebrafishRes_top[, c("geneset")], humanRes_top[, c("geneset")]) %>% dim
```

