---
title: "R Notebook"
output: html_notebook
---

```{r}
library(hgug4110b.db)
```

# Iron Overload

## 1. Import Dataset

The raw data was downloaded from GEO 
([GSE3573](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE3573)). 

```{r}
geo <- getGEO("GSE3573", GSEMatrix = TRUE)
```

Extract expression matrix and sample and probe annotations
```{r}
exprs <- geo$GSE3573_series_matrix.txt.gz@assayData$exprs
samples <- geo$GSE3573_series_matrix.txt.gz@phenoData@data
annot <- geo$GSE3573_series_matrix.txt.gz@featureData@data
dim(annot)
dim(exprs)
```

Formatting
```{r}
exprs <- exprs %>% set_rownames(annot$NAME)
samples %<>% dplyr::select(title, 
                           geo_accession, 
                           treatment_protocol_ch1) %>%
  dplyr::mutate(treatment = c(rep("Control", 3),
                              rep("Hemin", 3), 
                              rep("Serumfree", 3),
                              rep("Serumfree_and_FAC", 3)))
```

## 2. Principal Component Analysis
```{r}
pca <- exprs %>% t %>% prcomp()
summary(pca)
pca_plot_GSE3573 <- pca$x %>% as.data.frame %>% 
  rownames_to_column("geo_accession") %>% 
  left_join(samples, by = "geo_accession") %>%
  ggplot(aes(x = PC1, y = PC2, colour = treatment)) + 
  geom_point(size=3) + 
  geom_text_repel(aes(label = geo_accession)) +
  theme(aspect.ratio = 1) +
  labs(x = "Principal Component 1 (24.8%)", 
       y = "Principal Component 2 (13.8%)",
       colour = "Treatment")
pca_plot_GSE3573
export::graph2ppt(pca_plot_GSE3573, here::here("R/IronDepleted/fig/pca_plot_GSE3573"))
saveRDS(pca_plot_GSE3573, here::here("R/IronDepleted/fig/pca_plot_GSE3573.rds"))
#pca_plot_GSE3573 <- readRDS(here::here("R/IronDepleted/fig/pca_plot_GSE3573.rds"))
```

## 3. Annotation
```{r}
# Annotation ----------------------------------------------------------------------
# Check that the probe IDs are in the annotation package 
rownames(exprs) %in% keys(hgug4110b.db) %>% summary  # all TRUE

# Retrieve gene id annotations
annot <- AnnotationDbi::select(
  x = hgu133plus2.db, 
  keys = rownames(exprs),
  columns = c("PROBEID", "ENSEMBL", "ENTREZID", "SYMBOL"),
  keytype = "PROBEID"
)
all(rownames(exprs) %in% annot$PROBEID)  # TRUE

# Check for duplicate probe ids (assigned to different genes)
dup.ids <- annot$PROBEID[duplicated(annot$PROBEID)] %>% 
  unique %>%
  sort
length(dup.ids)  # 4430

# Example probe
annot[annot$PROBEID == dup.ids[2], ]

# Collapse down the duplicated genes so each row is 
# a unique probe ID
collapser <- function(x){
  x %>% unique %>% sort %>% paste(collapse = "|")
}
annot <- annot %>% 
  group_by(PROBEID) %>%
  summarise_each(funs(collapser)) %>% 
  ungroup

# Filter out probes which don't have ensembl IDs
annot %<>% dplyr::filter(!ENSEMBL == "")

head(annot)
dim(annot) # 43,285 probes

# We also would want to restrict the expression data to these probes
# and get the ordering to match
exprs <- normData@assayData$exprs %>% as.data.frame %>%
  rownames_to_column("PROBEID") %>% 
  dplyr::filter(PROBEID %in% annot$PROBEID) %>%
  column_to_rownames("PROBEID") %>%
  magrittr::extract(annot$PROBEID, )

# Check the ordering of rownames is exactly the same
(rownames(exprs)==annot$PROBEID) %>% summary  # all TRUE
```

## DE analysis

```{r}
# LIMMA ANALYSIS -------------------------------------------------------------------------------------------------------
# Bg: Need the following objects from limma analysis to perform IRE enrichment analysis:
#     voomData, design, contrasts

design <- model.matrix(~0 + treatment, data = samples) %>%
  set_colnames(gsub(x = colnames(.), pattern = "treatment", replacement = ""))

contrasts <- makeContrasts(
  levels = colnames(design), 
  IronOverload = Hemin - Control,
  IronDeficiency = Serumfree - Serumfree_and_FAC
)

fit <- lmFit(exprs, design) %>%
  contrasts.fit(contrasts)%>%
  eBayes()

hist(fit$Amean) # Many genes have low expression

results <- decideTests(fit, 
                       p.value = 0.05, 
                       adjust.method = "fdr")

results %>% summary()

volcanoplot(fit)

```

```{r}
# Combine the expression data with annotations
library(org.Hs.eg.db)
gene2trans <- as.data.frame(org.Hs.egENSEMBLTRANS) %>% left_join(as.data.frame(org.Hs.egENSEMBL))%>%
  set_colnames(c("ENTREZ", "ENSEMBL_ID", "ENSEMBL"))

datET <- exprs %>% 
  as.data.frame %>% 
  rownames_to_column("NAME") %>%
  left_join(annot, by = "NAME") %>% 
  left_join(gene2trans, by = "ENSEMBL_ID") %>%
  dplyr::filter(ENSEMBL != "" | !is.na(ENSEMBL)) %>%
  dplyr::distinct(NAME, .keep_all = TRUE) %>%
  set_rownames(.$NAME)

# Collapse rows
collapsed <- WGCNA::collapseRows(datET[,2:13], 
                          rowGroup = datET$ENSEMBL, 
                          rowID = rownames(datET), 
                          method ="MaxMean")

colExprs <- collapsed$datETcollapsed
 dim(colExprs)  # 3842

colAnnot <- data.frame(ENSEMBL = rownames(colExprs)) %>%
  left_join(annot, by = "ENSEMBL") %>%
  dplyr::distinct(ENSEMBL, .keep_all = TRUE)

newFit <- lmFit(colExprs, design) %>%
  contrasts.fit(contrasts) %>%
  eBayes()

results <- decideTests(newFit, 
                       p.value = 0.05, 
                       adjust.method = "fdr")

results %>% summary()


# IRE ENRICHMENT TESTING --------------------------------------------------------------

# Import in the enrichment function (fgsea; camera; mroast/fry) and the human gene sets
# with ENSEMBL ids. 
source(here::here("R/GSEA/combinedGSEA_ma.R"))
humanIreGenes <- readRDS(here::here("R/IREGenes/data/human_ireGenes.rds"))

# Build index specific to the ordering of the rownames in the expression matrix
humanIreIdx <- limma::ids2indices(humanIreGenes, 
                                  identifiers = rownames(colExprs))
  
ireEnr <- combinedGSEA_ma(colExprs, 
                          fit = newFit, 
                          design = design, 
                          contrasts = contrasts, 
                          idx = humanIreIdx)
# Results
ireEnr

# Export
saveRDS(ireEnr, here::here("R/IronDepleted/data/GSE3573_ireEnr.rds"))

```

